# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MediaMinder',
                'doc_host': 'https://theaboutbox.github.io',
                'git_url': 'https://github.com/theaboutbox/MediaMinder',
                'lib_path': 'MediaMinder'},
  'syms': {'MediaMinder.core': {'MediaMinder.core.foo': ('core.html#foo', 'MediaMinder/core.py')}}}
