# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_crewai2.ipynb.

# %% auto 0
__all__ = ['create_crew']

# %% ../nbs/06_crewai2.ipynb 3
from crewai import Agent

# %% ../nbs/06_crewai2.ipynb 5
from crewai import Task

# %% ../nbs/06_crewai2.ipynb 11
def create_crew(company: str, article: str, crew_llm: LLM) -> Crew:
    agents = SimpleAgents()
    tasks = SimpleTasks()
    
    classifier = agents.classifier(llm=crew_llm)
    sentiment = agents.sentiment(llm=crew_llm)
    products = agents.products(llm=crew_llm)
    competitors = agents.competitors(llm=crew_llm)
    events = agents.events(llm=crew_llm)
    
    classify = tasks.classify(classifier, company, article)
    sentiment_task = tasks.sentiment(sentiment, company)
    products_task = tasks.products(products, company)
    competitors_task = tasks.competitors(competitors, company)
    events_task = tasks.events(events, company)
    
    crew = Crew(
        name="Article Analysis Crew",
        tasks=[classify, sentiment_task, products_task, competitors_task, events_task],
        agents=[classifier, sentiment, products, competitors, events],
        process=Process.sequential,
        cache=True,
        memory=True,
        max_rpm=50,
        share_crew=True,
        llm=crew_llm,
    )
    
    return crew
