# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_get_page_data.ipynb.

# %% auto 0
__all__ = ['Article', 'extract_article']

# %% ../nbs/01_get_page_data.ipynb 4
import trafilatura

# %% ../nbs/01_get_page_data.ipynb 7
from datetime import date
import msgspec


# %% ../nbs/01_get_page_data.ipynb 9
class Article(msgspec.Struct):
    content: str
    metadata: str

def extract_article(html_content: str, date_params: dict = None) -> Article:
    if date_params is None:
        # set max date to today
        today = date.today()
        formatted_date = today.strftime("%Y-%m-%d")
        
        date_params = {"original_date": True, "extensive_search": True, "max_date": formatted_date}

    extracted_text = trafilatura.extract(html_content, date_extraction_params=date_params)
    metadata = trafilatura.extract_metadata(html_content, date_config=date_params)
    return Article(content=extracted_text, metadata=metadata.as_dict())

