# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_scrape_page.ipynb.

# %% auto 0
__all__ = ['scrape_url']

# %% ../nbs/02_scrape_page.ipynb 4
import requests
from rich.pretty import pprint
import os

# %% ../nbs/02_scrape_page.ipynb 5
def _scraping_bee_request(url: str, timeout=20):
    response = requests.get(
        url="https://app.scrapingbee.com/api/v1/",
        params={
            "api_key": os.environ['SCRAPING_BEE_API_KEY'],
            "url": url,
        },
        timeout=timeout,
    )
    response.raise_for_status()
    return response.text

# %% ../nbs/02_scrape_page.ipynb 6
def _scraping_ant_request(url, timeout: int = 40):
    response = requests.get(
        url="https://api.scrapingant.com/v2/general",
        params={
            "url": url,
            "x-api-key": os.environ['SCRAPING_ANT_API_KEY'],
        },
        timeout=timeout,
    )
    response.raise_for_status()
    return response.text

# %% ../nbs/02_scrape_page.ipynb 8
def scrape_url(url: str) -> str:
    #try:
    #    return _scraping_ant_request(url)
    #except Exception as e:
    #    print(e)
    #    return _scraping_bee_request(url)
    return _scraping_bee_request(url)
