# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_search.ipynb.

# %% auto 0
__all__ = ['SearchResult', 'SearchResults', 'run_query']

# %% ../nbs/03_search.ipynb 3
import requests
import msgspec
import os

# %% ../nbs/03_search.ipynb 9
class SearchResult(msgspec.Struct):
    title: str
    content: str
    url: str
    image_url: str
    source: str

    @classmethod
    def from_dict(cls, d):
        return cls(
            title=d["title"],
            content=d["content"],
            url=d["url"],
            image_url=d["img_src"],
            source=", ".join(d["engines"]),
        )


class SearchResults(msgspec.Struct):
    page: int
    results: list[SearchResult]

    @classmethod
    def from_list(cls, l: list[dict], page: int):
        return cls(
            page=page,
            results=[SearchResult.from_dict(d) for d in l],
        )

# %% ../nbs/03_search.ipynb 10
def run_query(query: str, page: int, time_range: str = "month") -> list[SearchResult]:
    api_endpoint = os.environ["SEARCH_ENDPOINT"]
    params = {
        "q": query,
        "format": "json",
        "language": "auto",
        "time_range": time_range,
        "safesearch": 0,
        "pageno": page,
    }
    response = requests.get(api_endpoint, params=params)
    if response.status_code == 200:
        page_results = response.json()
        return [SearchResult.from_dict(d) for d in page_results["results"]]
    else:
        return []
